import type { FormTemplateInput } from "@/lib/forms/fields";

const consent = {
  id: "souhlas",
  type: "consent" as const,
  label: "Souhlasím se zpracováním osobních údajů pro vyřízení tohoto podání.",
  description: "Údaje použije Klub československého vlčáka jen k vyřízení podání a evidenci, kterou podání vyžaduje.",
  placeholder: "",
  required: true,
  order: 100,
  options: [],
};

export const seedFormTemplates: FormTemplateInput[] = [
  {
    title: "Přihláška do klubu",
    slug: "prihlaska-do-klubu",
    description: "Žádost o členství. Po odeslání přijde žadateli e-mail s odkazem k potvrzení.",
    active: true,
    startsAt: "",
    endsAt: "",
    confirmationText: "Děkujeme. Podání bude platné po potvrzení z e-mailu a po schválení správou klubu.",
    approvalType: "single",
    notificationEmails: [],
    fields: [
      { id: "jmeno", type: "text", label: "Jméno a příjmení", description: "", placeholder: "", required: true, order: 1, options: [], binding: "party_a_name" },
      { id: "email", type: "email", label: "E-mail", description: "", placeholder: "", required: true, order: 2, options: [], binding: "party_a_email" },
      { id: "telefon", type: "tel", label: "Telefon", description: "", placeholder: "", required: true, order: 3, options: [] },
      { id: "adresa", type: "textarea", label: "Adresa", description: "", placeholder: "", required: true, order: 4, options: [] },
      { id: "pes", type: "text", label: "Jméno psa, pokud už nějakého máte", description: "", placeholder: "", required: false, order: 5, options: [] },
      consent,
    ],
  },
  {
    title: "Přihláška na akci",
    slug: "prihlaska-na-akci",
    description: "Přihláška na výstavu, bonitaci, svod nebo jinou klubovou akci.",
    active: true,
    startsAt: "",
    endsAt: "",
    confirmationText: "Přihláška čeká na potvrzení z vašeho e-mailu.",
    approvalType: "single",
    notificationEmails: [],
    fields: [
      { id: "jmeno", type: "text", label: "Jméno a příjmení", description: "", placeholder: "", required: true, order: 1, options: [], binding: "party_a_name" },
      { id: "email", type: "email", label: "E-mail", description: "", placeholder: "", required: true, order: 2, options: [], binding: "party_a_email" },
      { id: "telefon", type: "tel", label: "Telefon", description: "", placeholder: "", required: true, order: 3, options: [] },
      { id: "akce", type: "text", label: "Název akce", description: "", placeholder: "", required: true, order: 4, options: [] },
      { id: "pes", type: "dog", label: "Pes z databáze", description: "Pokud pes v databázi ještě není, uveďte ho do poznámky.", placeholder: "", required: false, order: 5, options: [] },
      { id: "poznamka", type: "textarea", label: "Poznámka", description: "", placeholder: "", required: false, order: 6, options: [] },
      consent,
    ],
  },
  {
    title: "Žádost o krycí list",
    slug: "zadost-o-kryci-list",
    description: "Žádost potvrzují obě strany: majitel feny a majitel psa. Každý dostane vlastní odkaz.",
    active: true,
    startsAt: "",
    endsAt: "",
    confirmationText: "Žádost bude uzavřena až po potvrzení obou stran.",
    approvalType: "dual",
    notificationEmails: [],
    fields: [
      { id: "majitel_feny", type: "text", label: "Majitel feny", description: "", placeholder: "", required: true, order: 1, options: [], binding: "party_a_name" },
      { id: "email_feny", type: "email", label: "E-mail majitele feny", description: "", placeholder: "", required: true, order: 2, options: [], binding: "party_a_email" },
      { id: "fena", type: "text", label: "Jméno feny", description: "", placeholder: "", required: true, order: 3, options: [] },
      { id: "majitel_psa", type: "text", label: "Majitel psa", description: "", placeholder: "", required: true, order: 4, options: [], binding: "party_b_name" },
      { id: "email_psa", type: "email", label: "E-mail majitele psa", description: "Na tuto adresu přijde odkaz ke kontrole a schválení.", placeholder: "", required: true, order: 5, options: [], binding: "party_b_email" },
      { id: "pes", type: "text", label: "Jméno psa", description: "", placeholder: "", required: true, order: 6, options: [] },
      { id: "termin", type: "date", label: "Předpokládaný termín krytí", description: "", placeholder: "", required: false, order: 7, options: [] },
      { id: "poznamka", type: "textarea", label: "Poznámka", description: "", placeholder: "", required: false, order: 8, options: [] },
      consent,
    ],
  },
  {
    title: "Oznámení narození vrhu",
    slug: "oznameni-narozeni-vrhu",
    description: "Hlášení vrhu potvrzuje chovatel a majitel otce vrhu.",
    active: true,
    startsAt: "",
    endsAt: "",
    confirmationText: "Hlášení se uzamkne po potvrzení obou stran.",
    approvalType: "dual",
    notificationEmails: [],
    fields: [
      { id: "chovatel", type: "text", label: "Chovatel", description: "", placeholder: "", required: true, order: 1, options: [], binding: "party_a_name" },
      { id: "email_chovatele", type: "email", label: "E-mail chovatele", description: "", placeholder: "", required: true, order: 2, options: [], binding: "party_a_email" },
      { id: "majitel_psa", type: "text", label: "Majitel otce vrhu", description: "", placeholder: "", required: true, order: 3, options: [], binding: "party_b_name" },
      { id: "email_psa", type: "email", label: "E-mail majitele otce", description: "", placeholder: "", required: true, order: 4, options: [], binding: "party_b_email" },
      { id: "matka", type: "text", label: "Matka", description: "", placeholder: "", required: true, order: 5, options: [] },
      { id: "otec", type: "text", label: "Otec", description: "", placeholder: "", required: true, order: 6, options: [] },
      { id: "datum", type: "date", label: "Datum narození", description: "", placeholder: "", required: true, order: 7, options: [] },
      { id: "psi", type: "number", label: "Počet narozených psů", description: "", placeholder: "", required: true, order: 8, options: [], validation: { min: 0, max: 20 } },
      { id: "feny", type: "number", label: "Počet narozených fen", description: "", placeholder: "", required: true, order: 9, options: [], validation: { min: 0, max: 20 } },
      { id: "misto", type: "text", label: "Město / region", description: "", placeholder: "", required: true, order: 10, options: [] },
      consent,
    ],
  },
  {
    title: "Záznam zdravotního výsledku",
    slug: "zdravotni-vysledek",
    description: "Podklad k vyšetření. Zveřejnění v databázi rozhodne správa klubu.",
    active: true,
    startsAt: "",
    endsAt: "",
    confirmationText: "Záznam čeká na potvrzení a na zpracování správou.",
    approvalType: "single",
    notificationEmails: [],
    fields: [
      { id: "jmeno", type: "text", label: "Jméno majitele", description: "", placeholder: "", required: true, order: 1, options: [], binding: "party_a_name" },
      { id: "email", type: "email", label: "E-mail", description: "", placeholder: "", required: true, order: 2, options: [], binding: "party_a_email" },
      { id: "pes", type: "text", label: "Jméno psa", description: "", placeholder: "", required: true, order: 3, options: [] },
      { id: "typ", type: "select", label: "Druh vyšetření", description: "", placeholder: "", required: true, order: 4, options: [
        { value: "rtg-hd", label: "RTG HD" },
        { value: "rtg-ed", label: "RTG ED" },
        { value: "dkk", label: "DKK" },
        { value: "dkl", label: "DKL" },
        { value: "jine", label: "Jiné" },
      ] },
      { id: "vysledek", type: "text", label: "Výsledek", description: "", placeholder: "", required: true, order: 5, options: [] },
      { id: "datum", type: "date", label: "Datum vyšetření", description: "", placeholder: "", required: true, order: 6, options: [] },
      { id: "priloha", type: "file", label: "Sken nebo PDF", description: "PDF, JPG, PNG nebo WEBP do 8 MB.", placeholder: "", required: false, order: 7, options: [] },
      consent,
    ],
  },
  {
    title: "Přidání chovatelské stanice",
    slug: "chovatelska-stanice",
    description: "Žádost o zveřejnění chovatelské stanice.",
    active: true,
    startsAt: "",
    endsAt: "",
    confirmationText: "Žádost čeká na potvrzení z e-mailu.",
    approvalType: "single",
    notificationEmails: [],
    fields: [
      { id: "jmeno", type: "text", label: "Jméno držitele stanice", description: "", placeholder: "", required: true, order: 1, options: [], binding: "party_a_name" },
      { id: "email", type: "email", label: "E-mail", description: "", placeholder: "", required: true, order: 2, options: [], binding: "party_a_email" },
      { id: "stanice", type: "text", label: "Název stanice", description: "", placeholder: "", required: true, order: 3, options: [] },
      { id: "region", type: "text", label: "Město / region", description: "", placeholder: "", required: true, order: 4, options: [] },
      { id: "web", type: "text", label: "Web", description: "", placeholder: "https://", required: false, order: 5, options: [] },
      consent,
    ],
  },
  {
    title: "Inzerát",
    slug: "inzerat",
    description: "Nabídka štěňat, krytí nebo jiný klubový inzerát. Zveřejnění schvaluje správa.",
    active: true,
    startsAt: "",
    endsAt: "",
    confirmationText: "Inzerát bude zveřejněn až po potvrzení a schválení správou.",
    approvalType: "single",
    notificationEmails: [],
    fields: [
      { id: "jmeno", type: "text", label: "Jméno", description: "", placeholder: "", required: true, order: 1, options: [], binding: "party_a_name" },
      { id: "email", type: "email", label: "E-mail", description: "", placeholder: "", required: true, order: 2, options: [], binding: "party_a_email" },
      { id: "nadpis", type: "text", label: "Nadpis", description: "", placeholder: "", required: true, order: 3, options: [] },
      { id: "text", type: "textarea", label: "Text inzerátu", description: "", placeholder: "", required: true, order: 4, options: [], validation: { minLength: 20, maxLength: 2000 } },
      { id: "foto", type: "photo", label: "Fotografie", description: "", placeholder: "", required: false, order: 5, options: [] },
      consent,
    ],
  },
  {
    title: "Žádost o individuální bonitaci",
    slug: "individualni-bonitace",
    description: "Žádost o bonitaci mimo společný termín.",
    active: true,
    startsAt: "",
    endsAt: "",
    confirmationText: "Žádost čeká na potvrzení z e-mailu.",
    approvalType: "single",
    notificationEmails: [],
    fields: [
      { id: "jmeno", type: "text", label: "Jméno majitele", description: "", placeholder: "", required: true, order: 1, options: [], binding: "party_a_name" },
      { id: "email", type: "email", label: "E-mail", description: "", placeholder: "", required: true, order: 2, options: [], binding: "party_a_email" },
      { id: "telefon", type: "tel", label: "Telefon", description: "", placeholder: "", required: true, order: 3, options: [] },
      { id: "pes", type: "text", label: "Jméno psa a číslo zápisu", description: "", placeholder: "", required: true, order: 4, options: [] },
      { id: "duvod", type: "textarea", label: "Důvod žádosti", description: "", placeholder: "", required: true, order: 5, options: [] },
      consent,
    ],
  },
];
